local f = io.open('Protection.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 Gurd.sh')
os.execute('killall -9 tg')
os.execute('rm -rf Protection.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('Protection.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 Gard.sh')
os.execute('screen ./Gurd.sh')
